# https://taskfile.dev
 
version: '3'

vars:
  PROJECT_DIR: .

tasks:
  default:
    desc: Show current app versions
    cmds:
      - task: version:show


  tdev:
    desc: Start Tauri development server
    cmds:
      - pnpm tauri dev
  ydev:
    desc: Start development server
    cmds:
      - pnpm dev  
  buildebug:
    desc: Start Tauri development server
    cmds:
      - pnpm tauri build --debug
  version:show:
    desc: Show versions in package.json, tauri.conf.json and Cargo.toml
    dir: '{{.PROJECT_DIR}}'
    cmds:
      - node scripts/version.mjs show

  v:
    desc: Set version in package.json, tauri.conf.json and Cargo.toml
    dir: '{{.PROJECT_DIR}}'
    vars:
      VERSION_ARG: '{{.CLI_ARGS | default .VERSION}}'
    cmds:
      - node scripts/version.mjs set {{.VERSION_ARG}}
